1: 
	javac -classpath /mnt/biginsights/opt/ibm/biginsights/IHC/hadoop-core-1.0.0.jar -d class/ Hoops.java
	jar -cvf Hoops.jar -C class/ .
2: 
	javac -classpath /mnt/biginsights/opt/ibm/biginsights/IHC/hadoop-core-1.0.0.jar -d class/ Triangles.java
	jar -cvf Triangles.jar -C class/ .
clean:
	rm -rf class/* 
